const char* gliderCells = R"""(
!Name: Glider
!Author: Richard K. Guy
!The smallest, most common, and first discovered spaceship.
!www.conwaylife.com/wiki/index.php?title=Glider
.O
..O
OOO
)""";

const char* fireShip = R"""(
! Fireship
! Simon Ekström
! https://conwaylife.com/wiki/Fireship
! https://conwaylife.com/patterns/fireship.cells
....O..O....
....O..O....
...O....O...
...O....O...
...O....O...
...O....O...
..OOO..OOO..
..O.OOOO.O..
...O....O...
............
............
.....OO.....
.....OO.....
.....OO.....
...O....O...
.OOO....OOO.
OOO......OOO
OO........OO
.OOOOOOOOOO.
..OOOOOOOO..
....OOOO....
)""";